### ISSUE TITLE
link in summary doesn't match the actual link

### ISSUE THREAD

**Issue by briandorsey** [neilmovva/pathfinder#1]
Link in summary is: http://www.sailresearch.com/pathfinder  (which is a 404), actual link appears to be: http://www.sailresearch.com/pathfinder.html

**Comment by neilmovva** [comment]
thanks brian - things are very much a work in progress, as you can see. I built the "Sail Research" webpages before having a solid foundation in web design/frameworks, so I have been reluctant to rework the mess of files currently live. Will overhaul that soon, but for now, the latest updates will always be on github and a project log I maintain on hackaday - https://hackaday.io/project/2372-pathfinder-haptic-navigation. Changing summary now.
